### ISSUE TITLE
 Setup Pipeline [Blocker]

### ISSUE THREAD

**Issue by talk2MeGooseman** [UCB201905FSF1Online-FHP/ChessProject#1]
Setup new Rails app, GitHub & Heroku account.

This is the first task! This is important & needs to get done quickly since it blocks all other tasks from starting. Make sure the students understand when a cards required tasks end.

    Create a new Rails app:
        Create a static landing page that just says “hello” or something.
        It doesn't have to look fancy.
    GitHub:
        Create a new GitHub organization: https://github.com/blog/674-introducing-organizations
        Come up with a team name first.
        Add other team members to the organization (have students share GitHub handles in chat)
    Heroku:
        Create a new Heroku App.
        Add other team members as collaborators (have students share heroku emails in chat)
    Share all of this info with the rest of the team. Everyone will then be able to collaborate on the project. Example: Working On Existing Projects https://online.bootcampspot.com/cheat-sheets/working-on-existing-projects

**Comment by PavaniPamarthy** [comment]
Hey @talk2MeGooseman  , I have completed the first task. Please let me know  of the next action before proceeding to Task 2.

**Comment by talk2MeGooseman** [comment]
Looks, good. Master branch will now be protected and you will have to start making branches and pull requests for each ticket of work. Feel free to start task 2 when you can.
