### ISSUE TITLE
Plan Out The Database Structure (Part I) [ Blocker ]

### ISSUE THREAD

**Issue by talk2MeGooseman** [UCB201905FSF1Online-FHP/ChessProject#4]
- This is the most complicated task.
- Use Google Sheets / Excel to map out all the fields you think we will need.
- Try to think through the easiest way to structure the Database for a normal chess game. Keep out things that are too many steps ahead (i.e. for castling you’ll need to know has the king moved yet. Nitpicky details like this aren’t important we just want to support a basic game of chess now, we’ll add those things later)
- After coming up with a plan for the database review it with a separate team member.
Share and after it is reviewed by the team send it to me and I (team leader) will review it.

The database structure can look like this (here is how we would do it for nomster): https://docs.google.com/spreadsheets/d/1lnECXUfdZLbDBLAilW_vXXl-1BJdut11gUu0GniifGQ/edit?usp=sharing

**Comment by PavaniPamarthy** [comment]
[Book1.xlsx](https://github.com/UCB201905FSF1Online-FHP/ChessProject/files/3720025/Book1.xlsx)

**Comment by talk2MeGooseman** [comment]
Updated sheet [Book1.xlsx](https://github.com/UCB201905FSF1Online-FHP/ChessProject/files/3720033/Book1.xlsx)
